### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by csherwood-usgs** [Coastal-Imaging-Research-Network/CIRN-Introduction-to-Quantitative-Coastal-Imaging-Toolbox#19]
Hey Brittany,
This is an awesome toolbox! I have successfully used it to do extrinsic calibrations and rectifications of our camera on the outer Cape: https://usgs.gov/caco01. Everything is easily laid out, and it is easy for my summer students to follow the steps. I have only found two typos, and my only other comment is that it would be nice to indent the code...and that is so easy in Matlab: ctrl-a, ctrl-i.

The typos are in C_singleExtrinsicSolution.m:
line 155  - Shouldn't that be "World Y Axis"
line 165  - Now in Section 5

Great job! Chris

**Comment by csherwood-usgs** [comment]
Do you know if anybody has translated the rectification functions to Python?

**Comment by burritobrittany** [comment]
Thanks @csherwood-usgs !!!

Thank you so much for the feedback!
We have not translated them. However, you are not the first to ask. I will ask around with my python friends :)

Best,
Brittany

**Comment by burritobrittany** [comment]
Didn't know about that cool indent trick! Thanks!
