### ISSUE TITLE
First Impressions... 

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/CIRN-Introduction-to-Quantitative-Coastal-Imaging-Toolbox#3]
Hi Brittany - 
I recently tested out your CIRN-BOOTCAMP-TOOLBOX to see what it does. 
So far I have only tried the "UAS Demo", but am looking forward to testing the fixed cam, and a few example sets of my own. I like it a lot. It must've been a tremendous amount of work!

Generally: It's super tidy! Logical, clear, well organized. Doesn't feel dense... light and fresh. Will be much easier for new members to grasp than the UAV-Toolbox. 

Here are a few things I noticed with fresh eyes (having no idea what the repo contained):

1. Probably needs a simple 'road map for dummies', i.e. First, do A. Then do B, etc. Do we still use E if making a birthday cake rather than breakfast pancakes (see "bootcampToolboxIntroduction.pptx" for food reference)?  

2. addpath to the repo code folder?   

3. I like that you list required functions in each script... It might need to be updated,  e.g. E_....m says 'none', but uses 'thresholdCenter.m'

4. imageRectifier: Neat visualization concept.  Maybe add a note to explain how to change the resolution (idxdy)? Maybe add 'm' unit to X and Y stats and plots?

5. Initially I found E to be confusing (SCP), just because I wasn't sure where the SCPs were or how to select them (i.e. thresholding, square, feature detection?), BUT after clicking blindly through it became clear... And it's better than the old UAV-Toolbox version. I just didn't know what to do to start or what it was expecting. Could use some brief instructions.

6. PixelInsts - is it possible to input a line of xyz values, e.g. beach topo transect? - doesn't seem so.
  Does it save an r structure (like PIXtoolbox)? - yes - "pixInst". Will be good to recall this later.  
  Can it automatically trim off pixels not in the oblique? 
  Can it write pixellists for hotm?

Awesome!!

**Comment by burritobrittany** [comment]
Thanks @SRHarrison !

So working on all of the above!

1. Working on it!
2. Done! I have a new branch (Bruder_NewFeaturesFixes) that I will create a pull request for soon.
3. Thanks...once the basic code is nailed down, I hope to do a big clean up and spot check for typos like that.
4. I am veering away from putting a unit on the plots/stats in case anyone is using feet. Maybe I will add [unit distance] or something. idxdy is currently specified in D_gridGenExampleRect. I see your point though where someone may want to down or up sample. It may just be simpler to keep it in one place though. Open for discussion!

5. In the new branch, I added more helpful hints on the first frame, like what is the SCP and suggested threshold values etc. So I hope this helps! Also, the manual when made will help too.

6. So it can get a topo line. It interpolates it from your input grid you specify. However, I should make it be more clear. So as of now it does not make an r structure. However, we are planning to add a wrapper function at the end of the toolbox that will make structures for cbathy and vbar, etc.  It trimmed pixels in the original development, however in my new branch I actually move this capability around into XYZ2distUV.  No pixel lists yet, probably in the wrapper function.

Thanks for the feedback! New pull request coming soon!
